version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /data:/data/mongo
  redis:
    container_name: redis_cache
    image: redis
    expose:
      - 6379